apiVersion: v1
kind: ReplicationController
metadata:
  name: grpc-server
  labels:
    name: grpc-server
spec:
  replicas: 2
  selector:
    name: grpc-server
  template:
    metadata:
      labels:
        name: grpc-server
    spec:
      containers:
      - name: master
        image: suecool/grpc-server
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-server
  labels:
    name: grpc-server
spec:
  ports:
    # the port that this service should serve on
  - port: 50051
    targetPort: 50051
  selector:
    name: grpc-server
